name: python-statistics
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy=1.21.*
  - scipy
  - pandas=1.4.*
  - matplotlib=3.5.*
  - xlrd
  - openpyxl
  - notebook
  - scikit-learn
  - statsmodels
